import { useEffect, useState, useRef } from 'react'
import { Plus, Trash2, Sparkles, ChevronDown, ChevronUp, Tag, Upload, FileText } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Separator } from '@/components/ui/separator'
import { toast } from 'sonner'
import { Note, Notebook, notesApi, uploadApi } from '@/lib/api'
import ReactMarkdown from 'react-markdown'

interface NotesPanelProps {
  notebook: Notebook
  onRefresh: () => void
}

export default function NotesPanel({ notebook, onRefresh }: NotesPanelProps) {
  const [notes, setNotes] = useState<Note[]>([])
  const [loading, setLoading] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [newTitle, setNewTitle] = useState('')
  const [newContent, setNewContent] = useState('')
  const [expandedNote, setExpandedNote] = useState<string | null>(null)
  const [deleteTarget, setDeleteTarget] = useState<Note | null>(null)
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [uploadDialogOpen, setUploadDialogOpen] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const [uploadTitle, setUploadTitle] = useState('')
  const fileInputRef = useRef<HTMLInputElement>(null)

  const fetchNotes = async () => {
    setLoading(true)
    try {
      const res = await notesApi.getByNotebook(notebook.id)
      setNotes(res.data)
    } catch {
      toast.error('Failed to load notes')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchNotes()
    setExpandedNote(null)
  }, [notebook.id])

  const handleCreate = async () => {
    if (!newTitle.trim() || !newContent.trim()) {
      toast.error('Please fill in both title and content')
      return
    }
    setGenerating(true)
    try {
      const res = await notesApi.create(notebook.id, newTitle, newContent)
      setNotes(prev => [res.data, ...prev])
      setNewTitle('')
      setNewContent('')
      setDialogOpen(false)
      toast.success('Note generated by AI!')
      onRefresh()
    } catch {
      toast.error('Failed to create note')
    } finally {
      setGenerating(false)
    }
  }

  const handleUploadPDF = async () => {
    if (!selectedFile) {
      toast.error('Please select a PDF file')
      return
    }
    setUploading(true)
    try {
      const res = await uploadApi.uploadPDF(selectedFile, notebook.id, uploadTitle)
      setNotes(prev => [res.data, ...prev])
      setSelectedFile(null)
      setUploadTitle('')
      setUploadDialogOpen(false)
      toast.success('PDF processed successfully!')
      onRefresh()
    } catch {
      toast.error('Failed to process PDF')
    } finally {
      setUploading(false)
    }
  }

  const handleDeleteClick = (note: Note) => {
    setDeleteTarget(note)
    setConfirmOpen(true)
  }

  const handleConfirmDelete = async () => {
    if (!deleteTarget) return
    try {
      await notesApi.delete(deleteTarget.id)
      setNotes(prev => prev.filter(n => n.id !== deleteTarget.id))
      toast.success('Note deleted')
    } catch {
      toast.error('Failed to delete note')
    } finally {
      setDeleteTarget(null)
      setConfirmOpen(false)
    }
  }

  const toggleExpand = (id: string) => {
    setExpandedNote(prev => prev === id ? null : id)
  }

  return (
    <>
      <div className="flex flex-col overflow-hidden" style={{ height: 'calc(100vh - 130px)' }}>
        <div className="p-4 flex items-center justify-between border-b border-gray-100 shrink-0">
          <p className="text-sm text-gray-500">{notes.length} note{notes.length !== 1 ? 's' : ''}</p>
          <div className="flex items-center gap-2">

            <Dialog open={uploadDialogOpen} onOpenChange={setUploadDialogOpen}>
              <DialogTrigger asChild>
                <Button size="sm" variant="outline" className="gap-2">
                  <Upload className="w-4 h-4" />
                  Upload PDF
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-md">
                <DialogHeader>
                  <DialogTitle className="flex items-center gap-2">
                    <FileText className="w-5 h-5 text-indigo-500" />
                    Upload PDF
                  </DialogTitle>
                </DialogHeader>
                <div className="space-y-4 pt-2">
                  <Input
                    placeholder="Note title (optional)"
                    value={uploadTitle}
                    onChange={e => setUploadTitle(e.target.value)}
                  />
                  <div
                    onClick={() => fileInputRef.current?.click()}
                    className={`border-2 border-dashed rounded-xl p-8 text-center cursor-pointer transition-colors ${
                      selectedFile
                        ? 'border-indigo-400 bg-indigo-50'
                        : 'border-gray-200 hover:border-indigo-300 hover:bg-gray-50'
                    }`}
                  >
                    <input
                      ref={fileInputRef}
                      type="file"
                      accept=".pdf"
                      className="hidden"
                      onChange={e => setSelectedFile(e.target.files?.[0] || null)}
                    />
                    {selectedFile ? (
                      <div className="flex items-center justify-center gap-2 text-indigo-600">
                        <FileText className="w-6 h-6" />
                        <span className="text-sm font-medium truncate max-w-48">{selectedFile.name}</span>
                      </div>
                    ) : (
                      <div>
                        <Upload className="w-8 h-8 text-gray-300 mx-auto mb-2" />
                        <p className="text-sm text-gray-500">Click to select a PDF file</p>
                        <p className="text-xs text-gray-400 mt-1">Max size 10MB</p>
                      </div>
                    )}
                  </div>
                  <div className="flex items-center gap-2 text-xs text-gray-400 bg-indigo-50 p-3 rounded-lg">
                    <Sparkles className="w-3.5 h-3.5 text-indigo-400 shrink-0" />
                    AI will extract text and generate structured notes automatically
                  </div>
                  <Button
                    onClick={handleUploadPDF}
                    disabled={uploading || !selectedFile}
                    className="w-full gap-2"
                  >
                    {uploading ? (
                      <>
                        <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                        Processing PDF...
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4" />
                        Generate Notes from PDF
                      </>
                    )}
                  </Button>
                </div>
              </DialogContent>
            </Dialog>

            <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
              <DialogTrigger asChild>
                <Button size="sm" className="gap-2">
                  <Plus className="w-4 h-4" />
                  Add Note
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-2xl">
                <DialogHeader>
                  <DialogTitle className="flex items-center gap-2">
                    <Sparkles className="w-5 h-5 text-blue-500" />
                    Generate AI Note
                  </DialogTitle>
                </DialogHeader>
                <div className="space-y-4 pt-2">
                  <Input
                    placeholder="Note title"
                    value={newTitle}
                    onChange={e => setNewTitle(e.target.value)}
                  />
                  <Textarea
                    placeholder="Paste your content here — lecture notes, article, topic description... AI will generate structured notes from it."
                    value={newContent}
                    onChange={e => setNewContent(e.target.value)}
                    rows={8}
                    className="resize-none"
                  />
                  <div className="flex items-center gap-2 text-xs text-gray-400 bg-blue-50 p-3 rounded-lg">
                    <Sparkles className="w-3.5 h-3.5 text-blue-400" />
                    AI will generate structured notes, a summary, and tags automatically
                  </div>
                  <Button onClick={handleCreate} disabled={generating} className="w-full gap-2">
                    {generating ? (
                      <>
                        <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4" />
                        Generate Note
                      </>
                    )}
                  </Button>
                </div>
              </DialogContent>
            </Dialog>

          </div>
        </div>

        <ScrollArea className="flex-1 p-4 h-0">
          {loading ? (
            <div className="flex items-center justify-center py-16">
              <div className="w-6 h-6 border-2 border-blue-500 border-t-transparent rounded-full animate-spin" />
            </div>
          ) : notes.length === 0 ? (
            <div className="text-center py-16 text-gray-400">
              <Sparkles className="w-10 h-10 mx-auto mb-3 text-gray-300" />
              <p className="text-sm">No notes yet. Add your first note!</p>
            </div>
          ) : (
            <div className="space-y-3 pb-4">
              {notes.map(note => (
                <Card key={note.id} className="border border-gray-200 shadow-sm hover:shadow-md transition-shadow">
                  <CardHeader className="pb-2 pt-4 px-4">
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1 min-w-0">
                        <h3 className="font-semibold text-gray-800 text-sm">{note.title}</h3>
                        {note.summary && (
                         <p className="text-xs text-gray-500 mt-1">{note.summary}</p>
                        )}
                      </div>
                      <div className="flex items-center gap-1 shrink-0">
                        <button
                          onClick={() => toggleExpand(note.id)}
                          className="text-gray-400 hover:text-gray-600 p-1 rounded hover:bg-gray-100"
                        >
                          {expandedNote === note.id ? (
                            <ChevronUp className="w-4 h-4" />
                          ) : (
                            <ChevronDown className="w-4 h-4" />
                          )}
                        </button>
                        <button
                          onClick={() => handleDeleteClick(note)}
                          className="text-gray-400 hover:text-red-500 p-1 rounded hover:bg-red-50"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>

                    {note.tags && note.tags.length > 0 && (
                      <div className="flex items-center gap-1 flex-wrap mt-2">
                        <Tag className="w-3 h-3 text-gray-400" />
                        {note.tags.map((tag, i) => (
                          <Badge key={i} variant="secondary" className="text-xs px-1.5 py-0">
                            {tag}
                          </Badge>
                        ))}
                      </div>
                    )}
                  </CardHeader>

                  {expandedNote === note.id && (
                    <>
                      <Separator />
                      <CardContent className="pt-4 pb-4 px-4">
                        <div className="max-h-96 overflow-y-auto pr-1">
                          <ReactMarkdown
                            components={{
                              h1: ({ children }) => (
                                <h1 className="text-base font-bold text-gray-900 mt-3 mb-1">{children}</h1>
                              ),
                              h2: ({ children }) => (
                                <h2 className="text-sm font-bold text-gray-800 mt-3 mb-1 border-b border-gray-100 pb-1">{children}</h2>
                              ),
                              h3: ({ children }) => (
                                <h3 className="text-sm font-semibold text-gray-700 mt-2 mb-1">{children}</h3>
                              ),
                              p: ({ children }) => (
                                <p className="text-xs text-gray-700 mb-2 leading-relaxed">{children}</p>
                              ),
                              ul: ({ children }) => (
                                <ul className="list-disc list-inside mb-2 space-y-0.5">{children}</ul>
                              ),
                              ol: ({ children }) => (
                                <ol className="list-decimal list-inside mb-2 space-y-0.5">{children}</ol>
                              ),
                              li: ({ children }) => (
                                <li className="text-xs text-gray-700 leading-relaxed ml-2">{children}</li>
                              ),
                              strong: ({ children }) => (
                                <strong className="font-semibold text-gray-900">{children}</strong>
                              ),
                              em: ({ children }) => (
                                <em className="italic text-gray-600">{children}</em>
                              ),
                              hr: () => <hr className="border-gray-200 my-2" />,
                              blockquote: ({ children }) => (
                                <blockquote className="border-l-2 border-blue-300 pl-3 italic text-gray-600 my-2 text-xs">{children}</blockquote>
                              ),
                              code: ({ children }) => (
                                <code className="bg-gray-100 text-blue-700 px-1 py-0.5 rounded text-xs font-mono">{children}</code>
                              ),
                            }}
                          >
                            {note.content}
                          </ReactMarkdown>
                        </div>
                      </CardContent>
                    </>
                  )}
                </Card>
              ))}
            </div>
          )}
        </ScrollArea>
      </div>

      <AlertDialog open={confirmOpen} onOpenChange={setConfirmOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Note</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete <span className="font-semibold text-gray-800">"{deleteTarget?.title}"</span>? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleConfirmDelete}
              className="bg-red-500 hover:bg-red-600 text-white"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  )
}